#!/usr/bin/gawk -f

# Include function libraries
@include "../lib/html.awk" ;
@include "../lib/utils.awk" ;
@include "../lib/lw.awk" ;

BEGIN{

  # setDB();  # not using this yet

  # GET or POST?
  # test with curl -d "a=b" [-G] <URL>
  RS = "\x04";
  if (ENVIRON["QUERY_STRING"]) {
    IN = ENVIRON["QUERY_STRING"]
  }
  else getline IN
  
  # READ QUERY STRING
  split(IN, query, "&");
  for (i in query) {
    split(query[i], tmpq, "=");
    f[tmpq[1]] = substr(urldecode(tmpq[2]),1,1000000); 
  }

  # DETERMINE AND EXECUTE METHOD
  if            (f["method"] == "validate")  validate();
  else if       (f["method"] == "html")      makehtml();

  # other/no arguments
  else system("echo -e 'Content-type: text/html\n'; cat index.html")
  
  exit ;

}
